"""
Node: generate_report

Assembles the final CostAnalysisReport from everything earlier nodes
produced. The executive summary is generated by the LLM when possible; on
failure we fall back to a short rule-based summary so the CLI / API always
return a valid report.
"""

import json
import re
from datetime import UTC, datetime

from iaccostagent.agent.state import IaCCostState
from iaccostagent.llm.prompts import REPORT_GENERATION_PROMPT
from iaccostagent.llm.provider import create_llm
from iaccostagent.models.schemas import (
    CloudProvider,
    CostAnalysisReport,
    OptimizationSuggestion,
    ResourceCost,
)

TOP_DRIVERS_COUNT = 5


def _extract_json(text: str) -> str:
    match = re.search(r"```(?:json)?\s*\n?(.*?)\n?\s*```", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return text.strip()


def _fallback_summary(
    total: float,
    top_drivers: list[ResourceCost],
    optimizations: list[OptimizationSuggestion],
    savings: float,
) -> str:
    if total == 0:
        return "No cost data available for this configuration."
    parts = [f"Estimated monthly cost is ${total:,.2f}."]
    if top_drivers:
        top = top_drivers[0]
        parts.append(
            f"Biggest cost driver: {top.resource.address} at ${top.monthly_cost:,.2f}/month "
            f"({top.percentage_of_total:.0f}% of total)."
        )
    if savings > 0:
        pct = savings / total * 100.0 if total > 0 else 0.0
        parts.append(f"Potential savings identified: ${savings:,.2f}/month ({pct:.0f}% reduction).")
    parts.append(f"{len(optimizations)} optimization suggestion(s) available.")
    return " ".join(parts)


async def generate_report_node(state: IaCCostState) -> dict:
    """Build the final CostAnalysisReport."""
    estimate = state.get("cost_estimate")
    patterns = state.get("patterns", [])
    optimizations = state.get("optimizations", [])
    llm_provider = state.get("llm_provider", "ollama/qwen3:8b")
    skip_llm = state.get("skip_llm", False)
    errors = list(state.get("errors", []))

    total = estimate.total_monthly_cost if estimate else 0.0

    top_drivers: list[ResourceCost] = []
    if estimate:
        top_drivers = sorted(estimate.resource_costs, key=lambda rc: rc.monthly_cost, reverse=True)[:TOP_DRIVERS_COUNT]

    total_savings = sum(o.estimated_monthly_savings for o in optimizations)
    savings_pct = (total_savings / total * 100.0) if total > 0 else 0.0

    provider: CloudProvider | None = estimate.provider if estimate else None
    region = estimate.region if estimate else state.get("region")

    # Try LLM summary; fall back on failure.
    summary = _fallback_summary(total, top_drivers, optimizations, total_savings)

    if estimate and total > 0 and not skip_llm:
        prompt = REPORT_GENERATION_PROMPT.format(
            project_path=state["project_path"],
            provider=provider.value if provider else "unknown",
            region=region or "unknown",
            total_monthly_cost=f"{total:.2f}",
            resource_count=len(estimate.resource_costs),
            top_drivers_formatted="\n".join(
                f"- {rc.resource.address}: ${rc.monthly_cost:.2f}/month ({rc.percentage_of_total:.1f}%)"
                for rc in top_drivers
            ),
            optimizations_formatted="\n".join(
                f"- {o.title} ({o.resource_address}): save ${o.estimated_monthly_savings:.2f}/month "
                f"[{o.risk.value} risk]"
                for o in optimizations
            ),
            savings=f"{total_savings:.2f}",
            savings_pct=f"{savings_pct:.1f}",
        )
        try:
            llm = create_llm(llm_provider)
            response = await llm.ainvoke(prompt)
            content = response.content if hasattr(response, "content") else str(response)
            parsed = json.loads(_extract_json(str(content)))
            llm_summary = parsed.get("summary")
            if isinstance(llm_summary, str) and llm_summary.strip():
                summary = llm_summary.strip()
        except Exception as e:
            errors.append(f"LLM report summary failed (using rule-based fallback): {e}")

    report = CostAnalysisReport(
        project_path=state["project_path"],
        analyzed_at=datetime.now(UTC),
        backend_used=state.get("backend", "infracost"),
        provider=provider,
        region=region,
        total_monthly_cost=total,
        resource_count=len(estimate.resource_costs) if estimate else len(state.get("resources", [])),
        top_cost_drivers=top_drivers,
        patterns_detected=patterns,
        optimizations=optimizations,
        total_potential_savings=total_savings,
        savings_percentage=savings_pct,
        executive_summary=summary,
        errors=errors,
    )

    return {
        "report": report,
        "current_node": "generate_report",
        "errors": errors,
    }
